name: Daily Energy Analysis

on:
  schedule:
    - cron: '0 5 * * *' # Action ED at 5:00 UTC
  workflow_dispatch: 

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Python 3.11 setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Dependencies installation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Config file creation from secrets 
        env:
          TERNA_CLIENT_ID: ${{ secrets.TERNA_CLIENT_ID }}
          TERNA_CLIENT_SECRET: ${{ secrets.TERNA_CLIENT_SECRET }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          ENTSOE_API_TOKEN: ${{ secrets.ENTSOE_API_TOKEN }}
        run: |
          echo "CLIENT_ID = '${TERNA_CLIENT_ID}'" > config.py
          echo "CLIENT_SECRET = '${TERNA_CLIENT_SECRET}'" >> config.py
          echo "ENTSOE_API_TOKEN = '${ENTSOE_API_TOKEN}'" >> config.py
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccountKey.json
          
      - name: Analysis script execution
        run: python3 nuclear_analyzer.py